name: module3_task3

on:
  push:
  schedule:
    - cron: "0 0 * * *"
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
      - name: Installing
        run: |
            cd module3_task3
            sudo ./setup.sh
      - name: Build
        run: |
            cd module3_task3
            make build
      - name: Post
        run: |
            cd module3_task3
            make POST_NAME=name POST_TITLE=title post
      - name: Package
        run: |
            cd module3_task3
            make package
      - name: Help
        run: |
            cd module3_task3
            make help
      - name: Clean
        run: |
            cd module3_task3
            make clean
      - name: Lint
        run: |
            cd module3_task3
            make lint
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            module3_task3/DEPLOY.md
            module3_task3/awesome-website.zip
